<a href="https://colab.research.google.com/github/cheongseungkyu/make-it-happen/blob/main/%EC%82%B0%EB%B6%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests

산림청 국립산림과학원_산불위험예보정보

산불위험지수(시도) 데이터 정보 조회

In [16]:
URL = ('http://apis.data.go.kr/1400377/forestPoint/'
      'forestPointListSidoSearch?'
      'serviceKey=INgUFCPLVXKA1R1IoOaejy9GNI%2BuFuWNZPPInGnjgr2XQQYmmq09MvpkvnykS3Hp5pd1TD1ysdH%2F1M5k9GghmQ%3D%3D'
      '&numOfRows=10'
      '&pageNo=1'
      '&localAreas=11,26'
      '&excludeForecast=0'
      '&_type=json')
response = requests.get(URL)

In [17]:
response

In [18]:
r = response.json()
r

{'response': {'body': {'items': {'item': [{'analdate': '2022-04-01 20',
      'area': '      60,571',
      'd1': 32,
      'd2': 60,
      'd3': 8,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 86,
      'meanavg': 59,
      'mini': 8,
      'regioncode': 11,
      'std': 6},
     {'analdate': '2022-04-02 00',
      'area': '      60,571',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 37,
      'meanavg': 23,
      'mini': 13,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-02 03',
      'area': '      60,571',
      'd1': 98,
      'd2': 2,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 58,
      'meanavg': 35,
      'mini': 20,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-02 06',
      'area': '      60,571',
      'd1': 0,
      'd2': 26,
      'd3': 70,
      'd4': 4,
      'doname': '서울특별시',
      'maxi': 93,
      'meanavg': 71,
      'mini': 53,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-02 09',
      'area': '      60,571',
      'd1': 1,
      'd2': 28,
      'd3': 67,
      'd4': 4,
      'doname': '서울특별시',
      'maxi': 93,
      'meanavg': 70,
      'mini': 46,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-03 00',
      'area': '      60,571',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 37,
      'meanavg': 23,
      'mini': 13,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-03 03',
      'area': '      60,571',
      'd1': 97,
      'd2': 3,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 58,
      'meanavg': 36,
      'mini': 20,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-03 06',
      'area': '      60,571',
      'd1': 1,
      'd2': 68,
      'd3': 31,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 86,
      'meanavg': 63,
      'mini': 41,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-03 09',
      'area': '      60,571',
      'd1': 0,
      'd2': 18,
      'd3': 78,
      'd4': 4,
      'doname': '서울특별시',
      'maxi': 93,
      'meanavg': 71,
      'mini': 53,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-01 20',
      'area': '      76,757',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 66,
      'meanavg': 45,
      'mini': 6,
      'regioncode': 26,
      'std': 7},
     {'analdate': '2022-04-02 00',
      'area': '      76,757',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 44,
      'meanavg': 25,
      'mini': 13,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-02 03',
      'area': '      76,757',
      'd1': 62,
      'd2': 36,
      'd3': 2,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 72,
      'meanavg': 48,
      'mini': 27,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-02 06',
      'area': '      76,757',
      'd1': 0,
      'd2': 44,
      'd3': 55,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 86,
      'meanavg': 66,
      'mini': 48,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-02 09',
      'area': '      76,757',
      'd1': 3,
      'd2': 61,
      'd3': 36,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 86,
      'meanavg': 63,
      'mini': 43,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-03 00',
      'area': '      76,757',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 44,
      'meanavg': 25,
      'mini': 13,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-03 03',
      'area': '      76,757',
      'd1': 44,
      'd2': 50,
      'd3': 6,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 72,
      'meanavg': 52,
      'mini': 27,
      'regioncode': 26,
      'std': 7},
     {'analdate': '2022-04-03 06',
      'area': '      76,757',
      'd1': 0,
      'd2': 27,
      'd3': 72,
      'd4': 2,
      'doname': '부산광역시',
      'maxi': 93,
      'meanavg': 70,
      'mini': 50,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-03 09',
      'area': '      76,757',
      'd1': 1,
      'd2': 33,
      'd3': 65,
      'd4': 1,
      'doname': '부산광역시',
      'maxi': 93,
      'meanavg': 69,
      'mini': 44,
      'regioncode': 26,
      'std': 7}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 18},
  'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'}}}

http://jsonviewer.stack.hu/

In [19]:
print(type(r))

<class 'dict'>

In [25]:
items = r['response']['body']['items']
items

{'item': [{'analdate': '2022-04-01 20',
   'area': '      60,571',
   'd1': 32,
   'd2': 60,
   'd3': 8,
   'd4': 0,
   'doname': '서울특별시',
   'maxi': 86,
   'meanavg': 59,
   'mini': 8,
   'regioncode': 11,
   'std': 6},
  {'analdate': '2022-04-02 00',
   'area': '      60,571',
   'd1': 100,
   'd2': 0,
   'd3': 0,
   'd4': 0,
   'doname': '서울특별시',
   'maxi': 37,
   'meanavg': 23,
   'mini': 13,
   'regioncode': 11,
   'std': 5},
  {'analdate': '2022-04-02 03',
   'area': '      60,571',
   'd1': 98,
   'd2': 2,
   'd3': 0,
   'd4': 0,
   'doname': '서울특별시',
   'maxi': 58,
   'meanavg': 35,
   'mini': 20,
   'regioncode': 11,
   'std': 5},
  {'analdate': '2022-04-02 06',
   'area': '      60,571',
   'd1': 0,
   'd2': 26,
   'd3': 70,
   'd4': 4,
   'doname': '서울특별시',
   'maxi': 93,
   'meanavg': 71,
   'mini': 53,
   'regioncode': 11,
   'std': 5},
  {'analdate': '2022-04-02 09',
   'area': '      60,571',
   'd1': 1,
   'd2': 28,
   'd3': 67,
   'd4': 4,
   'doname': '서울특별시',
   'maxi': 93,
   'meanavg': 70,
   'mini': 46,
   'regioncode': 11,
   'std': 5},
  {'analdate': '2022-04-03 00',
   'area': '      60,571',
   'd1': 100,
   'd2': 0,
   'd3': 0,
   'd4': 0,
   'doname': '서울특별시',
   'maxi': 37,
   'meanavg': 23,
   'mini': 13,
   'regioncode': 11,
   'std': 5},
  {'analdate': '2022-04-03 03',
   'area': '      60,571',
   'd1': 97,
   'd2': 3,
   'd3': 0,
   'd4': 0,
   'doname': '서울특별시',
   'maxi': 58,
   'meanavg': 36,
   'mini': 20,
   'regioncode': 11,
   'std': 5},
  {'analdate': '2022-04-03 06',
   'area': '      60,571',
   'd1': 1,
   'd2': 68,
   'd3': 31,
   'd4': 0,
   'doname': '서울특별시',
   'maxi': 86,
   'meanavg': 63,
   'mini': 41,
   'regioncode': 11,
   'std': 5},
  {'analdate': '2022-04-03 09',
   'area': '      60,571',
   'd1': 0,
   'd2': 18,
   'd3': 78,
   'd4': 4,
   'doname': '서울특별시',
   'maxi': 93,
   'meanavg': 71,
   'mini': 53,
   'regioncode': 11,
   'std': 5},
  {'analdate': '2022-04-01 20',
   'area': '      76,757',
   'd1': 100,
   'd2': 0,
   'd3': 0,
   'd4': 0,
   'doname': '부산광역시',
   'maxi': 66,
   'meanavg': 45,
   'mini': 6,
   'regioncode': 26,
   'std': 7},
  {'analdate': '2022-04-02 00',
   'area': '      76,757',
   'd1': 100,
   'd2': 0,
   'd3': 0,
   'd4': 0,
   'doname': '부산광역시',
   'maxi': 44,
   'meanavg': 25,
   'mini': 13,
   'regioncode': 26,
   'std': 6},
  {'analdate': '2022-04-02 03',
   'area': '      76,757',
   'd1': 62,
   'd2': 36,
   'd3': 2,
   'd4': 0,
   'doname': '부산광역시',
   'maxi': 72,
   'meanavg': 48,
   'mini': 27,
   'regioncode': 26,
   'std': 6},
  {'analdate': '2022-04-02 06',
   'area': '      76,757',
   'd1': 0,
   'd2': 44,
   'd3': 55,
   'd4': 0,
   'doname': '부산광역시',
   'maxi': 86,
   'meanavg': 66,
   'mini': 48,
   'regioncode': 26,
   'std': 6},
  {'analdate': '2022-04-02 09',
   'area': '      76,757',
   'd1': 3,
   'd2': 61,
   'd3': 36,
   'd4': 0,
   'doname': '부산광역시',
   'maxi': 86,
   'meanavg': 63,
   'mini': 43,
   'regioncode': 26,
   'std': 6},
  {'analdate': '2022-04-03 00',
   'area': '      76,757',
   'd1': 100,
   'd2': 0,
   'd3': 0,
   'd4': 0,
   'doname': '부산광역시',
   'maxi': 44,
   'meanavg': 25,
   'mini': 13,
   'regioncode': 26,
   'std': 6},
  {'analdate': '2022-04-03 03',
   'area': '      76,757',
   'd1': 44,
   'd2': 50,
   'd3': 6,
   'd4': 0,
   'doname': '부산광역시',
   'maxi': 72,
   'meanavg': 52,
   'mini': 27,
   'regioncode': 26,
   'std': 7},
  {'analdate': '2022-04-03 06',
   'area': '      76,757',
   'd1': 0,
   'd2': 27,
   'd3': 72,
   'd4': 2,
   'doname': '부산광역시',
   'maxi': 93,
   'meanavg': 70,
   'mini': 50,
   'regioncode': 26,
   'std': 6},
  {'analdate': '2022-04-03 09',
   'area': '      76,757',
   'd1': 1,
   'd2': 33,
   'd3': 65,
   'd4': 1,
   'doname': '부산광역시',
   'maxi': 93,
   'meanavg': 69,
   'mini': 44,
   'regioncode': 26,
   'std': 7}]}

items는 list로 되어있음!!