<a href="https://colab.research.google.com/github/cheongseungkyu/make-it-happen/blob/main/%EC%82%B0%EB%B6%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import requests

In [14]:
import pandas as pd

In [18]:
!pip install gradio

Requirement already satisfied: gradio in /usr/local/lib/python3.7/dist-packages (2.9.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.7/dist-packages (from gradio) (7.1.2)
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.7/dist-packages (from gradio) (3.14.1)
Requirement already satisfied: python-multipart in /usr/local/lib/python3.7/dist-packages (from gradio) (0.0.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from gradio) (2.23.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from gradio) (3.2.2)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.7/dist-packages (from gradio) (0.17.6)
Requirement already satisfied: pydub in /usr/local/lib/python3.7/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: analytics-python in /usr/local/lib/python3.7/dist-packages (from gradio) (1.4.0)
Requirement already satisfied: paramiko in /usr/local/lib/python3.7/dist-packages (from gradio) (2.10.3)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.7/dist-packages (from gradio) (0.3.0)
Requirement already satisfied: orjson in /usr/local/lib/python3.7/dist-packages (from gradio) (3.6.7)
Requirement already satisfied: fastapi in /usr/local/lib/python3.7/dist-packages (from gradio) (0.75.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from gradio) (1.21.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from gradio) (1.3.5)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.7/dist-packages (from gradio) (3.8.1)
Requirement already satisfied: markdown-it-py[linkify,plugins] in /usr/local/lib/python3.7/dist-packages (from gradio) (2.0.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp->gradio) (6.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from aiohttp->gradio) (1.3.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->gradio) (2.0.12)
Requirement already satisfied: asynctest==0.13.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->gradio) (0.13.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->gradio) (1.7.2)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.7/dist-packages (from aiohttp->gradio) (1.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.7/dist-packages (from aiohttp->gradio) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->gradio) (21.4.0)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from aiohttp->gradio) (3.10.0.2)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp->gradio) (2.10)
Requirement already satisfied: monotonic>=1.5 in /usr/local/lib/python3.7/dist-packages (from analytics-python->gradio) (1.6)
Requirement already satisfied: python-dateutil>2.1 in /usr/local/lib/python3.7/dist-packages (from analytics-python->gradio) (2.8.2)
Requirement already satisfied: backoff==1.10.0 in /usr/local/lib/python3.7/dist-packages (from analytics-python->gradio) (1.10.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from analytics-python->gradio) (1.15.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->gradio) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->gradio) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->gradio) (3.0.4)
Requirement already satisfied: starlette==0.17.1 in /usr/local/lib/python3.7/dist-packages (from fastapi->gradio) (0.17.1)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in /usr/local/lib/python3.7/dist-packages (from fastapi->gradio) (1.9.0)
Requirement already satisfied: anyio<4,>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from starlette==0.17.1->fastapi->gradio) (3.5.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.7/dist-packages (from anyio<4,>=3.0.0->starlette==0.17.1->fastapi->gradio) (1.2.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.7/dist-packages (from markdown-it-py[linkify,plugins]->gradio) (0.1.0)
Requirement already satisfied: linkify-it-py~=1.0 in /usr/local/lib/python3.7/dist-packages (from markdown-it-py[linkify,plugins]->gradio) (1.0.3)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.7/dist-packages (from markdown-it-py[linkify,plugins]->gradio) (0.3.0)
Requirement already satisfied: uc-micro-py in /usr/local/lib/python3.7/dist-packages (from linkify-it-py~=1.0->markdown-it-py[linkify,plugins]->gradio) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->gradio) (3.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->gradio) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->gradio) (1.4.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->gradio) (2018.9)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from paramiko->gradio) (1.5.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib/python3.7/dist-packages (from paramiko->gradio) (36.0.2)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.7/dist-packages (from paramiko->gradio) (3.2.0)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.7/dist-packages (from bcrypt>=3.1.3->paramiko->gradio) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko->gradio) (2.21)
Requirement already satisfied: asgiref>=3.4.0 in /usr/local/lib/python3.7/dist-packages (from uvicorn->gradio) (3.5.0)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.7/dist-packages (from uvicorn->gradio) (7.1.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.7/dist-packages (from uvicorn->gradio) (0.13.0)

In [19]:
import gradio as gd

산림청 국립산림과학원_산불위험예보정보

산불위험지수(시도) 데이터 정보 조회

In [7]:
URL = ('http://apis.data.go.kr/1400377/forestPoint/'
      'forestPointListSidoSearch?'
      'serviceKey=INgUFCPLVXKA1R1IoOaejy9GNI%2BuFuWNZPPInGnjgr2XQQYmmq09MvpkvnykS3Hp5pd1TD1ysdH%2F1M5k9GghmQ%3D%3D'
      '&numOfRows=10'
      '&pageNo=1'
      '&localAreas=11,26'
      '&excludeForecast=0'
      '&_type=json')
response = requests.get(URL)

In [8]:
response

In [9]:
r = response.json()
r

{'response': {'body': {'items': {'item': [{'analdate': '2022-04-02 07',
      'area': '      60,571',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 51,
      'meanavg': 24,
      'mini': 9,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-02 12',
      'area': '      60,571',
      'd1': 24,
      'd2': 51,
      'd3': 25,
      'd4': 1,
      'doname': '서울특별시',
      'maxi': 86,
      'meanavg': 57,
      'mini': 32,
      'regioncode': 11,
      'std': 6},
     {'analdate': '2022-04-02 15',
      'area': '      60,571',
      'd1': 97,
      'd2': 3,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 58,
      'meanavg': 32,
      'mini': 13,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-02 18',
      'area': '      60,571',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 51,
      'meanavg': 27,
      'mini': 13,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-02 21',
      'area': '      60,571',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 44,
      'meanavg': 24,
      'mini': 13,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-03 12',
      'area': '      60,571',
      'd1': 22,
      'd2': 56,
      'd3': 22,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 86,
      'meanavg': 57,
      'mini': 32,
      'regioncode': 11,
      'std': 6},
     {'analdate': '2022-04-03 15',
      'area': '      60,571',
      'd1': 96,
      'd2': 4,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 65,
      'meanavg': 31,
      'mini': 13,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-03 18',
      'area': '      60,571',
      'd1': 99,
      'd2': 1,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 51,
      'meanavg': 27,
      'mini': 13,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-03 21',
      'area': '      60,571',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '서울특별시',
      'maxi': 44,
      'meanavg': 23,
      'mini': 13,
      'regioncode': 11,
      'std': 5},
     {'analdate': '2022-04-02 07',
      'area': '      76,757',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 51,
      'meanavg': 26,
      'mini': 6,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-02 12',
      'area': '      76,757',
      'd1': 53,
      'd2': 42,
      'd3': 6,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 72,
      'meanavg': 50,
      'mini': 29,
      'regioncode': 26,
      'std': 7},
     {'analdate': '2022-04-02 15',
      'area': '      76,757',
      'd1': 97,
      'd2': 3,
      'd3': 0,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 58,
      'meanavg': 33,
      'mini': 13,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-02 18',
      'area': '      76,757',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 51,
      'meanavg': 29,
      'mini': 13,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-02 21',
      'area': '      76,757',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 51,
      'meanavg': 26,
      'mini': 13,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-03 12',
      'area': '      76,757',
      'd1': 61,
      'd2': 38,
      'd3': 1,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 72,
      'meanavg': 48,
      'mini': 29,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-03 15',
      'area': '      76,757',
      'd1': 99,
      'd2': 1,
      'd3': 0,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 51,
      'meanavg': 31,
      'mini': 13,
      'regioncode': 26,
      'std': 6},
     {'analdate': '2022-04-03 18',
      'area': '      76,757',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 51,
      'meanavg': 26,
      'mini': 13,
      'regioncode': 26,
      'std': 7},
     {'analdate': '2022-04-03 21',
      'area': '      76,757',
      'd1': 100,
      'd2': 0,
      'd3': 0,
      'd4': 0,
      'doname': '부산광역시',
      'maxi': 44,
      'meanavg': 25,
      'mini': 13,
      'regioncode': 26,
      'std': 6}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 18},
  'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'}}}

http://jsonviewer.stack.hu/

In [10]:
print(type(r))

<class 'dict'>

In [95]:
items = r['response']['body']['items']['item']
items

[{'analdate': '2022-04-02 07',
  'area': '      60,571',
  'd1': 100,
  'd2': 0,
  'd3': 0,
  'd4': 0,
  'doname': '서울특별시',
  'maxi': 51,
  'meanavg': 24,
  'mini': 9,
  'regioncode': 11,
  'std': 5},
 {'analdate': '2022-04-02 12',
  'area': '      60,571',
  'd1': 24,
  'd2': 51,
  'd3': 25,
  'd4': 1,
  'doname': '서울특별시',
  'maxi': 86,
  'meanavg': 57,
  'mini': 32,
  'regioncode': 11,
  'std': 6},
 {'analdate': '2022-04-02 15',
  'area': '      60,571',
  'd1': 97,
  'd2': 3,
  'd3': 0,
  'd4': 0,
  'doname': '서울특별시',
  'maxi': 58,
  'meanavg': 32,
  'mini': 13,
  'regioncode': 11,
  'std': 5},
 {'analdate': '2022-04-02 18',
  'area': '      60,571',
  'd1': 100,
  'd2': 0,
  'd3': 0,
  'd4': 0,
  'doname': '서울특별시',
  'maxi': 51,
  'meanavg': 27,
  'mini': 13,
  'regioncode': 11,
  'std': 5},
 {'analdate': '2022-04-02 21',
  'area': '      60,571',
  'd1': 100,
  'd2': 0,
  'd3': 0,
  'd4': 0,
  'doname': '서울특별시',
  'maxi': 44,
  'meanavg': 24,
  'mini': 13,
  'regioncode': 11,
  'std': 5},
 {'analdate': '2022-04-03 12',
  'area': '      60,571',
  'd1': 22,
  'd2': 56,
  'd3': 22,
  'd4': 0,
  'doname': '서울특별시',
  'maxi': 86,
  'meanavg': 57,
  'mini': 32,
  'regioncode': 11,
  'std': 6},
 {'analdate': '2022-04-03 15',
  'area': '      60,571',
  'd1': 96,
  'd2': 4,
  'd3': 0,
  'd4': 0,
  'doname': '서울특별시',
  'maxi': 65,
  'meanavg': 31,
  'mini': 13,
  'regioncode': 11,
  'std': 5},
 {'analdate': '2022-04-03 18',
  'area': '      60,571',
  'd1': 99,
  'd2': 1,
  'd3': 0,
  'd4': 0,
  'doname': '서울특별시',
  'maxi': 51,
  'meanavg': 27,
  'mini': 13,
  'regioncode': 11,
  'std': 5},
 {'analdate': '2022-04-03 21',
  'area': '      60,571',
  'd1': 100,
  'd2': 0,
  'd3': 0,
  'd4': 0,
  'doname': '서울특별시',
  'maxi': 44,
  'meanavg': 23,
  'mini': 13,
  'regioncode': 11,
  'std': 5},
 {'analdate': '2022-04-02 07',
  'area': '      76,757',
  'd1': 100,
  'd2': 0,
  'd3': 0,
  'd4': 0,
  'doname': '부산광역시',
  'maxi': 51,
  'meanavg': 26,
  'mini': 6,
  'regioncode': 26,
  'std': 6},
 {'analdate': '2022-04-02 12',
  'area': '      76,757',
  'd1': 53,
  'd2': 42,
  'd3': 6,
  'd4': 0,
  'doname': '부산광역시',
  'maxi': 72,
  'meanavg': 50,
  'mini': 29,
  'regioncode': 26,
  'std': 7},
 {'analdate': '2022-04-02 15',
  'area': '      76,757',
  'd1': 97,
  'd2': 3,
  'd3': 0,
  'd4': 0,
  'doname': '부산광역시',
  'maxi': 58,
  'meanavg': 33,
  'mini': 13,
  'regioncode': 26,
  'std': 6},
 {'analdate': '2022-04-02 18',
  'area': '      76,757',
  'd1': 100,
  'd2': 0,
  'd3': 0,
  'd4': 0,
  'doname': '부산광역시',
  'maxi': 51,
  'meanavg': 29,
  'mini': 13,
  'regioncode': 26,
  'std': 6},
 {'analdate': '2022-04-02 21',
  'area': '      76,757',
  'd1': 100,
  'd2': 0,
  'd3': 0,
  'd4': 0,
  'doname': '부산광역시',
  'maxi': 51,
  'meanavg': 26,
  'mini': 13,
  'regioncode': 26,
  'std': 6},
 {'analdate': '2022-04-03 12',
  'area': '      76,757',
  'd1': 61,
  'd2': 38,
  'd3': 1,
  'd4': 0,
  'doname': '부산광역시',
  'maxi': 72,
  'meanavg': 48,
  'mini': 29,
  'regioncode': 26,
  'std': 6},
 {'analdate': '2022-04-03 15',
  'area': '      76,757',
  'd1': 99,
  'd2': 1,
  'd3': 0,
  'd4': 0,
  'doname': '부산광역시',
  'maxi': 51,
  'meanavg': 31,
  'mini': 13,
  'regioncode': 26,
  'std': 6},
 {'analdate': '2022-04-03 18',
  'area': '      76,757',
  'd1': 100,
  'd2': 0,
  'd3': 0,
  'd4': 0,
  'doname': '부산광역시',
  'maxi': 51,
  'meanavg': 26,
  'mini': 13,
  'regioncode': 26,
  'std': 7},
 {'analdate': '2022-04-03 21',
  'area': '      76,757',
  'd1': 100,
  'd2': 0,
  'd3': 0,
  'd4': 0,
  'doname': '부산광역시',
  'maxi': 44,
  'meanavg': 25,
  'mini': 13,
  'regioncode': 26,
  'std': 6}]

items는 list로 되어있음!!

In [99]:
import pandas as pd

items = r['response']['body']['items']['item']

analdate = [item['analdate'] for item in items]
doname = [item['doname'] for item in items]
d1 = [item['d1'] for item in items]
d2 = [item['d2'] for item in items]
d3 = [item['d3'] for item in items]
d4 = [item['d4'] for item in items]
meanavg = [item['meanavg'] for item in items]

analdate = pd.Series(analdate)
doname = pd.Series(doname)
d1 = pd.Series(d1)
d2 = pd.Series(d2)
d3 = pd.Series(d3)
d4 = pd.Series(d4)
meanavg = pd.Series(meanavg)

df = pd.DataFrame({'doname' : doname, 'analdate' : analdate, 'd1' : d1, 'd2' : d2, 'd3' : d3, 'd4' : d4, 'meanavg' : meanavg})

doname : 산불위험지역 시도 명칭
analdate : 데이터기준일자
d1 : 산불위험예보지수 낮음
d2 : 산불위험예보지수 다소높음
d3:  산불위험예보지수 높음
d4:  산불위험예보지수 매우높음
meanavg : 산불위험예보지수 평균

In [100]:
df

   doname       analdate   d1  d2  d3  d4  meanavg
0   서울특별시  2022-04-02 07  100   0   0   0       24
1   서울특별시  2022-04-02 12   24  51  25   1       57
2   서울특별시  2022-04-02 15   97   3   0   0       32
3   서울특별시  2022-04-02 18  100   0   0   0       27
4   서울특별시  2022-04-02 21  100   0   0   0       24
5   서울특별시  2022-04-03 12   22  56  22   0       57
6   서울특별시  2022-04-03 15   96   4   0   0       31
7   서울특별시  2022-04-03 18   99   1   0   0       27
8   서울특별시  2022-04-03 21  100   0   0   0       23
9   부산광역시  2022-04-02 07  100   0   0   0       26
10  부산광역시  2022-04-02 12   53  42   6   0       50
11  부산광역시  2022-04-02 15   97   3   0   0       33
12  부산광역시  2022-04-02 18  100   0   0   0       29
13  부산광역시  2022-04-02 21  100   0   0   0       26
14  부산광역시  2022-04-03 12   61  38   1   0       48
15  부산광역시  2022-04-03 15   99   1   0   0       31
16  부산광역시  2022-04-03 18  100   0   0   0       26
17  부산광역시  2022-04-03 21  100   0   0   0       25